### ISSUE TITLE
[Feature] Add firefox support

### ISSUE THREAD

**Issue by approvedpr** [Niek/playwright-addons#1]
Would highly appreciate it if you could add also support for playwright-firefox

**Comment by Niek** [comment]
It should work fine, just change `chromium` to `firefox` in the example script. If you encounter any issues, set the environment variable `DEBUG=pw:browser*` when executing node in order to see a debug log.

**Comment by approvedpr** [comment]
I am aware of how to use firefox in playwright but it seems like the evasions dont have a effect/dont work on firefox.

This is for example from a firefox instance with your script and some things made by me. Nothing has a effect.

![image](https://user-images.githubusercontent.com/57367608/86132586-5edd6200-bae7-11ea-9614-3102871cf3f5.png)

**Comment by Pizzacus** [comment]
That's because [nearly no evasions are ported yet](https://github.com/Niek/playwright-addons/blob/master/stealth/evasions.js). 

Although, the webdriver removal was added and you'll notice it passes this test. So it definitely has an effect.

Maybe it should be made clearer this project isn't very usable yet. Still, playwright-addons is very promising! I am very grateful someone is not only taking the torch from puppeteer-extra and its plugins, but also porting them to Playwright! But of course, this is gonna need a bit of time. <sup>Although I do hope as much as you do that this project won't disappear into the darkness.</sup>

**Comment by Niek** [comment]
What @Pizzacus said - the evasions are very limited now. I'll try to port a bunch of other evasions now. But obviously the Chrome object won't be present, as it's Firefox (the nannysoft site is specifically for Chrome).
The WebGL part is because Firefox doesn't support WebGL in headless mode (see [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1375585))- if you start it in regular mode it should work.

I'll add some Docker instructions to the README as well.

**Comment by approvedpr** [comment]
Ah ok then it was just a missunderstanding on my side. Thx for your both time! Looking forward to the future of this project and maybe I will also do some pulls whenever I have time

**Comment by Niek** [comment]
@all-contributors please add @SentoxAIO  for ideas
